import streamlit as st
import pandas as pd
import os

# Routine per caricare file dati unico e separare le due sezioni "General Data" e
# "Piping Data" generando i rispettivi CSV sotto files.
def loadData():

    # Funzione per verificare se il file è stato generato da "HeatLoss4"
    def verifica_file(df):

        if 'DatiCaricati' not in st.session_state:
            st.session_state.DatiCaricati = False
            
        # Trova la colonna che contiene il titolo della app
        
        colonna_heatloss = [col for col in df.columns if "Pflex1" in col]
        
        print ("colonna Pflex1", colonna_heatloss)
        if len(colonna_heatloss) == 0:
            # Se non trova la colonna, significa che il file non è stato generato correttamente
            st.warning("File not generated by Pflex1.")
            return None
        else:
            # Estrarre la data e l'ora dalla colonna
            colonna_info = colonna_heatloss[0]
            st.success(f"File correctly generated by Pflex1.")
            
            # Estrai la data e l'ora dal nome della colonna
            data_ora = colonna_info.split(' - ')[1]
            st.write(f"Creation Date & Time: {data_ora}")
            return data_ora

    # Funzione per separare i dati in base alla colonna che contiene "PiCa1"
    def separa_dati(df):
        # Trova l'indice della colonna che contiene "HeatLoss4"
        
        colonne_heatloss = [col for col in df.columns if "Pflex1" in col]
        colonna_sep1 = [col for col in df.columns if "separator_1" in col]
        colonna_sep2 = [col for col in df.columns if "separator_2" in col]
        colonna_sep3 = [col for col in df.columns if "separator_3" in col]
        colonna_sep4 = [col for col in df.columns if "separator_4" in col]
        colonna_sep5 = [col for col in df.columns if "separator_5" in col]
        colonna_sep6 = [col for col in df.columns if "separator_6" in col]

        
        if len(colonne_heatloss) == 0:
            st.error("No reference to Pflex1 app has been found.")
            return None, None, None, None, None
        
        colonna_heatloss_idx = colonne_heatloss[0]  # Nome della colonna "Pflex1"
        idx = df.columns.get_loc(colonna_heatloss_idx)  # Ottieni l'indice numerico della colonna
        idx_sep1 = df.columns.get_loc(colonna_sep1[0])
        idx_sep2 = df.columns.get_loc(colonna_sep2[0])
        idx_sep3 = df.columns.get_loc(colonna_sep3[0])
        idx_sep4 = df.columns.get_loc(colonna_sep4[0])
        idx_sep5 = df.columns.get_loc(colonna_sep5[0])
        idx_sep6 = df.columns.get_loc(colonna_sep6[0])

        #print ("indice colonna PiCa1", idx)
        #print ("indice colonna sep1", idx_sep1)
        #print ("indice colonna sep2", idx_sep2)
        #print ("indice colonna sep3", idx_sep3)
        #print ("indice colonna sep4", idx_sep4)
        #print ("indice colonna sep5", idx_sep5)
        #print ("indice colonna sep6", idx_sep6)

        # Separa i tre set di dati
        dati_generali = df.iloc[:, idx+1:idx_sep1].dropna(how='all')  # Dati fino alla colonna Pflex1
        dati_geo = df.iloc[:, idx_sep1+1: idx_sep2].dropna(how='all')  # Dati dopo sep1 e prima di sep2
        dati_concrete = df.iloc[:, idx_sep2+1: idx_sep3].dropna(how='all')  # Dati dopo sep2 e prima di sep3
        dati_steel = df.iloc[:, idx_sep3+1: idx_sep4].dropna(how='all')  # Dati dopo sep3 e prima di sep4
        dati_reinf_layers = df.iloc[:, idx_sep4+1: idx_sep5].dropna(how='all')  # Dati dopo sep4 e prima di sep5
        dati_load = df.iloc[:, idx_sep5+1: idx_sep6].dropna(how='all')  # Dati dopo sep5 e prima di sep6
        dati_loadsMR = df.iloc[:, idx_sep6+1: ].dropna(how='all')  # Dati dopo sep6

        #if "Rating" in dati_components.columns:
        #    dati_components["Rating"] = (
        #    pd.to_numeric(dati_components["Rating"], errors="coerce")
        #    .dropna()
        #    .astype(int)
        #    )

        return dati_generali, dati_geo, dati_concrete, dati_steel, dati_reinf_layers, dati_load, dati_loadsMR

    # -----------------------------------------------------------------------------------------
    # ***   Carica il file unito tramite uploader   ***
    # -----------------------------------------------------------------------------------------

    uploaded_file = st.file_uploader("Select a valid PiCa1 data file", type="csv")

    if uploaded_file is not None:
        # Leggi il file caricato in un DataFrame
        df_unito = pd.read_csv(uploaded_file)
                
        # Verifica se il file è stato generato dalla app che si sta utilizzando
        #     
        data_ora = verifica_file(df_unito)
    
        if data_ora:
            # Mostra un'anteprima del file solo se la verifica è andata a buon fine
            #st.write("Single File:")
            #st.dataframe(df_unito)

            #  --------- Separa i dati ----------
            dati_generali, dati_geo, dati_concrete, dati_steel, dati_reinf_layers, dati_load, dati_loadsMR = separa_dati(df_unito)
            
            if dati_generali is not None and dati_geo is not None:
                st.session_state.DatiCaricati = True
                dati_generali_vis = dati_generali.loc[:, ~dati_generali.columns.str.contains('^Unnamed')]
                dati_geo_vis = dati_geo.loc[:, ~dati_geo.columns.str.contains('^Unnamed')]
                dati_concrete_vis = dati_concrete.loc[:, ~dati_concrete.columns.str.contains('^Unnamed')]
                dati_steel_vis = dati_steel.loc[:, ~dati_steel.columns.str.contains('^Unnamed')]
                dati_reinf_layers_vis = dati_reinf_layers.loc[:, ~dati_reinf_layers.columns.str.contains('^Unnamed')]
                dati_load_vis = dati_load.loc[:, ~dati_load.columns.str.contains('^Unnamed')]
                dati_loadsMR_vis = dati_loadsMR.loc[:, ~dati_loadsMR.columns.str.contains('^Unnamed')]
                
                # Mostra un'anteprima dei dati separati
                st.write("General Data:")
                st.dataframe(dati_generali_vis)
                
                st.write("Geometry Data:")
                st.dataframe(dati_geo_vis)

                st.write("Concrete Data:")
                st.dataframe(dati_concrete_vis)

                st.write("Steel Data:")
                st.dataframe(dati_steel_vis)

                st.write("Reinforcement Layers Data:")
                st.dataframe(dati_reinf_layers_vis)

                st.write("Load Data:")
                st.dataframe(dati_load_vis)

                st.write("LoadsMR Data:")
                st.dataframe(dati_loadsMR_vis)

                                
                # Salva i file CSV localmente o su un percorso remoto
                # In questo esempio, i file vengono salvati localmente

                sessionDir = "sessions"

                               
                fileDatiGenerali = os.path.join(sessionDir, f"DatiGenerali_{st.session_state.session_id}.csv")
                fileDatiGeo = os.path.join(sessionDir, f"DatiGeo_{st.session_state.session_id}.csv")
                fileConcrete = os.path.join(sessionDir, f"concrete_{st.session_state.session_id}.csv")
                fileSteel = os.path.join(sessionDir, f"steel_{st.session_state.session_id}.csv")
                fileReinfLayers = os.path.join(sessionDir, f"Reinf_layers_{st.session_state.session_id}.csv")
                fileLoads = os.path.join(sessionDir, f"DatiLoad_{st.session_state.session_id}.csv")
                fileLoadsMR = os.path.join(sessionDir, f"loadsMR_{st.session_state.session_id}.csv")

                dati_generali.to_csv(fileDatiGenerali, index=False)
                dati_geo.to_csv(fileDatiGeo, index=False)   
                dati_concrete.to_csv(fileConcrete, index=False)
                dati_steel.to_csv(fileSteel, index=False)
                dati_reinf_layers.to_csv(fileReinfLayers, index=False)
                dati_load.to_csv(fileLoads, index=False)
                dati_loadsMR.to_csv(fileLoadsMR, index=False)
                
                st.success("General, Material data, Geometry and reinforcement Data -> loaded successfully!")


